### ISSUE TITLE
License for this code?

### ISSUE THREAD

**Issue by stefan-muc** [MatrixManAtYrService/md_htmldoc#1]
Hi MatrixManAtYrService,

your code looks quite interesting to fit to the problem I have. 
I discovered that your code doesn't state under which license it's released.

Would you be willing to release it under an open source license? See https://choosealicense.com/ for different licenses - if you want to be mentioned but permit everything else, I would suggest [MIT](https://choosealicense.com/licenses/mit/) license.

Thanks in advance!

**Comment by MatrixManAtYrService** [comment]
I'm happy to hear that you think it will be useful.  I've added the MIT license, as you've suggested.

**Comment by MatrixManAtYrService** [comment]
Perhaps I should warn you, it has been years since I thought about this project.  I think that it was working when I last left it, but I'm not totally sure, and I can't promise to be very useful when it comes to support.  Still, if issues come up, I'll do my best.

**Comment by stefan-muc** [comment]
Yeah I saw that last commit is about three years ago, and this is the first issue created for your code. I don't expect exhaustive support.

Thanks for adding the license! It's a way better feeling when using the code.

I think of porting the code to pure python (currently it's a mix between python and shell code) so it's platform independent, but I can't promise anything here. I just thought: The way you did it sounds good, I want to use that as draft.

**Comment by MatrixManAtYrService** [comment]
Pure python sounds better.  If I were doing it again from scratch, that's what I would do.

When I built this it was because I wanted to be using github (with in-source documentation wiki-like-action) but I was stuck with something else.  I wanted to build the wiki _now_ and so that we could switch to github _later_.  Later never ended up happening.

Now that I think of it, if I could go back and do it again, I'd probably not bother with the html conversion at all and have readers of the documentation run https://github.com/joeyespo/grip to view it.  Not sure if that applies to your use case, but thought I'd mention it.

**Comment by stefan-muc** [comment]
As for now I will stick to a shell script as I got it to work, and it also works on Windows (using git bash). Let's see if it is worth the additional effort to port it to pure Python

Thanks for the link to the other tool - that doesn't fit my use case as the user would have to know git and how to checkout a repository.
